eval/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('', include('quiz.urls', namespace='quiz')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quiz/urls.py
from django.urls import path
from .views import (
    quiz_view,
    render_pdf_view,
    result_view,
    delete_eval,
    thank,
)

app_name = 'quiz'

urlpatterns = [
    path('', quiz_view, name='quiz-view'),
    path('results/', result_view, name='result-view'),
    path('delete/<str:pk>/', delete_eval, name='delete-eval'),
    path("eval/<str:pk>/", render_pdf_view, name='eval-view'),
    path("thank/", thank, name='thank-view'),
]

quiz/models.py
from django.db import models


class Quiz(models.Model):
    # En tête
    FV_CHOICES = (
        ('Présentiel', 'Présentiel'),
        ('Visio', 'Visio'),
    )
    stage = models.CharField(choices=FV_CHOICES, max_length=200, null=True, blank=True)
    stage_name = models.CharField(max_length=200, null=True, blank=True)
    start_date = models.DateField(max_length=200, null=True, blank=True)
    end_date = models.DateField(max_length=200, null=True, blank=True)
    place = models.CharField(max_length=200, null=True, blank=True)
    teacher = models.CharField(max_length=200, null=True, blank=True)
    # Organisation
    organization1 = models.CharField(max_length=200, null=True, blank=True)
    org_comment1 = models.CharField(max_length=200, null=True, blank=True)
    organization2 = models.CharField(max_length=200, null=True, blank=True)
    org_comment2 = models.CharField(max_length=200, null=True, blank=True)
    organization3 = models.CharField(max_length=200, null=True, blank=True)
    org_comment3 = models.CharField(max_length=200, null=True, blank=True)
    # Formation
    formation1 = models.CharField(max_length=200, null=True, blank=True)
    for_comment1 = models.CharField(max_length=200, null=True, blank=True)
    formation2 = models.CharField(max_length=200, null=True, blank=True)
    for_comment2 = models.CharField(max_length=200, null=True, blank=True)
    formation3 = models.CharField(max_length=200, null=True, blank=True)
    for_comment3 = models.CharField(max_length=200, null=True, blank=True)
    formation4 = models.CharField(max_length=200, null=True, blank=True)
    for_comment4 = models.CharField(max_length=200, null=True, blank=True)
    formation5 = models.CharField(max_length=200, null=True, blank=True)
    for_comment5 = models.CharField(max_length=200, null=True, blank=True)
    formation6 = models.CharField(max_length=200, null=True, blank=True)
    for_comment6 = models.CharField(max_length=200, null=True, blank=True)
    # Formateur(s)
    teacher1 = models.CharField(max_length=200, null=True, blank=True)
    tea_comment1 = models.CharField(max_length=200, null=True, blank=True)
    teacher2 = models.CharField(max_length=200, null=True, blank=True)
    tea_comment2 = models.CharField(max_length=200, null=True, blank=True)
    teacher3 = models.CharField(max_length=200, null=True, blank=True)
    tea_comment3 = models.CharField(max_length=200, null=True, blank=True)
    teacher4 = models.CharField(max_length=200, null=True, blank=True)
    tea_comment4 = models.CharField(max_length=200, null=True, blank=True)
    # Appréciation générale
    appreciation1 = models.CharField(max_length=200, null=True, blank=True)
    ap_comment1 = models.CharField(max_length=200, null=True, blank=True)
    appreciation2 = models.CharField(max_length=200, null=True, blank=True)
    ap_comment2 = models.CharField(max_length=200, null=True, blank=True)
    # Recommandation de la formamtion
    recommendation2 = models.CharField(max_length=200, null=True, blank=True)
    # AUTO-ÉVALUATION DES ACQUIS
    acquis1 = models.CharField(max_length=200, null=True, blank=True)
    acquis2 = models.CharField(max_length=200, null=True, blank=True)
    acquis3 = models.CharField(max_length=200, null=True, blank=True)
    acquis_comment = models.CharField(max_length=200, null=True, blank=True)
    # Autres besoins de la formation
    other_formation2 = models.CharField(max_length=200, null=True, blank=True)
    other_formation_comment = models.CharField(max_length=200, null=True, blank=True)
    # Types, autres besoins de la formation
    other_formation_type2 = models.CharField(max_length=200, null=True, blank=True)
    other_formation_type_comment = models.CharField(max_length=200, null=True, blank=True)
    # PARTICIPANT
    name = models.CharField(max_length=200, null=True, blank=True)
    function = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=200, null=True, blank=True)
    email = models.CharField(max_length=200, null=True, blank=True)
    company = models.CharField(max_length=200, null=True, blank=True)
    company_activity = models.CharField(max_length=200, null=True, blank=True)
    total_company = models.CharField(max_length=200, null=True, blank=True)
    total_establishment = models.CharField(max_length=200, null=True, blank=True)
    election_date = models.DateField(max_length=200, null=True, blank=True)
    # Comment avez-vous connu ce stage
    find = models.CharField(max_length=200, null=True, blank=True)
    find_comment = models.CharField(max_length=200, null=True, blank=True)
    # created
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

quiz/forms.py
from django import forms
from django.forms import ModelForm
from .models import Quiz


class DateInput(forms.DateInput):
    input_type = 'date'


class QuizForm(forms.ModelForm):
    EVAL_CHOICES = (
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
    )
    BOOL_CHOICES = (
        ('Oui', 'Oui'),
        ('Non', 'Non'),
    )
    CHECK_CHOICES = (
        ('Rôle et fonctionnement du CSE', 'Rôle et fonctionnement du CSE'),
        ('SSCT', 'SSCT'),
        ('Référent harcèlement sexuel', 'Référent harcèlement sexuel'),
        ('Représentant de proximité', 'Représentant de proximité'),
        ('DUERP', 'DUERP'),
        ('Environnement', 'Environnement'),
        ('AUTRES', 'AUTRES'),
    )
    TYPE_CHOICES = (
        ('Assistance juridique', 'Assistance juridique'),
        ('Communication / négociation', 'Communication / négociation'),
        ('Expertise SSCT', 'Expertise SSCT'),
        ('Expertise comptable', 'Expertise comptable'),
        ('Autres', 'Autres'),
    )
    FIND_CHOICES = (
        ('Site internet', 'Site internet'),
        ('Mailing', 'Mailing'),
        ('Entreprise ayant déjà participé à un stage SICOGE', 'Entreprise ayant déjà participé à un stage SICOGE'),
        ('Autre', 'Autre'),
    )
    # Organisation
    organization1 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=EVAL_CHOICES,
    )
    organization2 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=EVAL_CHOICES,
    )
    organization3 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=EVAL_CHOICES,
    )
    # Formation
    formation1 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=EVAL_CHOICES,
    )
    formation2 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=EVAL_CHOICES,
    )
    formation3 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=EVAL_CHOICES,
    )
    formation4 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=EVAL_CHOICES,
    )
    formation5 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=EVAL_CHOICES,
    )
    formation6 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=EVAL_CHOICES,
    )
    # Formateur(s)
    teacher1 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=EVAL_CHOICES,
    )
    teacher2 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=EVAL_CHOICES,
    )
    teacher3 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=EVAL_CHOICES,
    )
    teacher4 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=EVAL_CHOICES,
    )
    # Appréciation générale
    appreciation1 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=EVAL_CHOICES,
    )
    appreciation2 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=EVAL_CHOICES,
    )
    # AUTO-ÉVALUATION DES ACQUIS
    acquis1 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=EVAL_CHOICES,
    )
    acquis2 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=EVAL_CHOICES,
    )
    acquis3 = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=EVAL_CHOICES,
    )
    # Autres besoins de la formation
    other_formation2 = forms.MultipleChoiceField(
        required=False,
        widget=forms.CheckboxSelectMultiple,
        choices=CHECK_CHOICES,
    )
    # Types, autres besoins de la formation
    other_formation_type2 = forms.MultipleChoiceField(
        required=False,
        widget=forms.CheckboxSelectMultiple,
        choices=TYPE_CHOICES,
    )
    # Comment avez-vous connu ce stage
    find = forms.MultipleChoiceField(
        required=False,
        widget=forms.CheckboxSelectMultiple,
        choices=FIND_CHOICES,
    )

    class Meta:
        model = Quiz
        fields = '__all__'
        widgets = {
            'start_date': DateInput(attrs={'type': 'text'}),
            'end_date': DateInput(attrs={'type': 'text'}),
            'election_date': DateInput(attrs={'type': 'text'}),
            'stage': forms.RadioSelect,
        }

quiz/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from django.core.paginator import Paginator
from .models import Quiz
from .forms import QuizForm
from quiz.utils import generate_pdf
# decorators
from django.contrib.auth.decorators import login_required
from authentication.decorators import allowed_users
from django.views.decorators.csrf import csrf_protect


# Create your views here.

@csrf_protect
def quiz_view(request):
    form = QuizForm()
    if request.method == 'POST':
        form = QuizForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('quiz:thank-view')
    context = {
        'form': form,
    }
    return render(request, 'quiz/quiz.html', context)


@login_required(login_url='login')
def result_view(request):
    results = Quiz.objects.all()
    context = {
        'results': results,
    }
    return render(request, 'quiz/result.html', context)


@login_required(login_url='login')
@allowed_users(allowed_roles=['team'])
def render_pdf_view(request, pk):
    """
    student eval pdf views
     """
    eval = get_object_or_404(Quiz, id=pk)
    # other_formations = list(eval.other_formation2)
    author = eval.name if eval.name else 'NR'
    context = {
        # 'other_formations': other_formations,
        'eval': eval,
    }
    template_path = 'quiz/render_pdf.html'
    pdf_name = f'Fiche-eval-de-{author}-du-{eval.created.day}-{eval.created.month}-{eval.created.year}'
    # return render(request, template_path, context)
    return generate_pdf(request, template_path, pdf_name, context)


@login_required(login_url='login')
@allowed_users(allowed_roles=['team'])
@csrf_protect
def delete_eval(request, pk):
    result = Quiz.objects.get(id=pk)
    if request.method == "POST":
        result.delete()
        return redirect('quiz:result-view')
    context = {
        'result': result,
    }
    return render(request, 'quiz/delete.html', context)


def thank(request):
    context = {
        'sms': "Merci d'avoir participer à l'évaluation de notre formation."
    }
    return render(request, 'quiz/thank.html', context)

quiz/templates/quiz/delete.html
<div class="modal">
  <form method="POST" action="{% url 'quiz:delete-eval' result.id %}" enctype="multipart/form-data" class="ui form">
    {% csrf_token %}
    <div class="header">
      <h2>Suppression d'un résultat de l'évaluation de satisfaction</h2>
    </div>
    <div class="content">
      <span>
        Etes-vous sûre de vouloir supprimer le résultat de
        {% if result.name %} l'évaluation de {{ result.name }}{% else %}cette évaluation{% endif %}  ?
      </span>
    </div>
    <div class="formBtn actions">
      <a href="{% url 'quiz:result-view' %}"><span class="modal-close">Annuler</span></a>
      <button class="confirm-btn delete " type="submit">Supprimer</button>
    </div>
  </form>
</div>

quiz/templates/quiz/result.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title %}
Resultats eval
{% endblock title %}
{% block content %}
{% load static %}
<nav class="navbar navbar-expand-lg ">
  <img src="{% static 'icons/logo.png' %}">
  <span class="hello-msg">Bonjour, {{request.user}}</span>
  <span><a class="hello-msg logout-btn" href="{% url 'logout' %}">Se déconnecter</a></span>
</nav>
<div class="table-responsive">
  {% include 'modal/modal.html' %}
  <table>
    <thead class="table-header">
    <tr>
      <th>Formation</th>
      <th>Réalisation</th>
      <th class="result-date">Date début</th>
      <th class="result-date">Date fin</th>
      <th>Lieu</th>
      <th>Formateur(s)</th>
      <th>Stagiaire</th>
      <th>Résultat</th>
      <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    {% for result in results %}
    <tr>
      <td>{{ result.stage_name }}</td>
      <td>{{ result.stage }}</td>
      <td class="result-date">
        {% language 'fr' %}
        {{ result.start_date | date:'d / m / y'}}
        {% endlanguage %}
      </td>
      <td class="result-date">
        {% language 'fr' %}
        {{ result.end_date | date:'d / m / y'}}
        {% endlanguage %}
      </td>
      <td>{{ result.place }}</td>
      <td>{{ result.teacher }}</td>
      {% if result.name %}
      <td>{{ result.name }}</td>
      {% else %}
      <td>--</td>
      {% endif %}
      <td>
        <a href="{% url 'quiz:eval-view' result.id %}" target="_blank">
          <button class="export">Export pdf</button>
        </a>
      </td>
      <td>
        <a href="{% url 'quiz:delete-eval' result.id %}">
          <button data-target="modal1"
                  class="open-modal delete-eval"
                  data-popup-url="{% url 'quiz:delete-eval' result.id %}"
          >
            Supprimer
          </button>
        </a>
      </td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
<!--{% include 'paginator.html' %}-->
{% endblock content %}

quiz/templates/quiz/thank.html
{% extends "base.html" %}
{% load static %}
{% load materializecss %}
{% load i18n %}
{% block title %}
  Evaluation enrégistrée avec succès
{% endblock title %}
{% block content %}
<div>
  <div class="evalQuiz">
    <h3>{{sms}}</h3>
    <a href="https://www.sicoge.com/" target="_blank">
      <div class="image">
        <img src="{% static './icons/logo.png' %}" alt="">
      </div>
    </a>
  </div>
</div>
{% endblock content %}